---
title: "Specification curve/multiverse analysis for Foody et al. (2013) and unpublished replication"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

# Acknowledgements

Code adapted from [Craig Sewall's code](https://github.com/cjsewall9/sm-gdp-multiverse).

# TODO

- Specification curve y axis line is too far from plot, can't seem to rectify this.

```{r, include=FALSE}

knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

```

# Dependencies and functions

```{r}

# dependencies

library(tidyverse)
library(knitr)
library(kableExtra)
library(janitor)
library(forcats)
library(ggtext)
library(patchwork)

```

# Get data

```{r}

data_combined <- 
  bind_rows(
    read_csv("foody et al 2013 publication/analysis/tables/table_1.csv",
             show_col_types = FALSE) |>
      mutate(study = "original",
             multiple_testing_corrections = FALSE, 
             control_for_baseline = FALSE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g, lower, upper),
    read_csv("foody et al 2013 publication/analysis/tables/table_2.csv",
             show_col_types = FALSE) |>
      mutate(study = "original",
             multiple_testing_corrections = FALSE, 
             control_for_baseline = FALSE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g, lower, upper),
    read_csv("foody et al 2013 publication/analysis/tables/table_3.csv",
             show_col_types = FALSE) |>
      mutate(study = "original",
             multiple_testing_corrections = FALSE, 
             control_for_baseline = TRUE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g = adjusted_hedges_g, lower = adjusted_lower, upper = adjusted_upper),
    read_csv("foody et al 2013 publication/analysis/tables/table_1_bonferroni.csv",
             show_col_types = FALSE) |>
      mutate(study = "original",
             multiple_testing_corrections = TRUE, 
             control_for_baseline = FALSE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g, lower, upper),
    read_csv("foody et al 2013 publication/analysis/tables/table_2_bonferroni.csv",
             show_col_types = FALSE) |>
      mutate(study = "original",
             multiple_testing_corrections = TRUE, 
             control_for_baseline = FALSE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g, lower, upper),
    read_csv("foody et al 2013 publication/analysis/tables/table_3_bonferroni.csv",
             show_col_types = FALSE) |>
      mutate(study = "original",
             multiple_testing_corrections = TRUE, 
             control_for_baseline = TRUE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g = adjusted_hedges_g, lower = adjusted_lower, upper = adjusted_upper),
    
    read_csv("foody 2013 thesis experiment 10/analysis/tables/table_1.csv",
             show_col_types = FALSE) |>
      mutate(study = "replication",
             multiple_testing_corrections = FALSE, 
             control_for_baseline = FALSE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g, lower, upper),
    read_csv("foody 2013 thesis experiment 10/analysis/tables/table_2.csv",
             show_col_types = FALSE) |>
      mutate(study = "replication",
             multiple_testing_corrections = FALSE, 
             control_for_baseline = FALSE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g, lower, upper),
    read_csv("foody 2013 thesis experiment 10/analysis/tables/table_3.csv",
             show_col_types = FALSE) |>
      mutate(study = "replication",
             multiple_testing_corrections = FALSE, 
             control_for_baseline = TRUE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g = adjusted_hedges_g, lower = adjusted_lower, upper = adjusted_upper),
    read_csv("foody 2013 thesis experiment 10/analysis/tables/table_1_bonferroni.csv",
             show_col_types = FALSE) |>
      mutate(study = "replication",
             multiple_testing_corrections = TRUE, 
             control_for_baseline = FALSE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g, lower, upper),
    read_csv("foody 2013 thesis experiment 10/analysis/tables/table_2_bonferroni.csv",
             show_col_types = FALSE) |>
      mutate(study = "replication",
             multiple_testing_corrections = TRUE, 
             control_for_baseline = FALSE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g, lower, upper),
    read_csv("foody 2013 thesis experiment 10/analysis/tables/table_3_bonferroni.csv",
             show_col_types = FALSE) |>
      mutate(study = "replication",
             multiple_testing_corrections = TRUE, 
             control_for_baseline = TRUE) |>
      select(study, interval, outcome_measure, control_for_baseline, multiple_testing_corrections, 
             hedges_g = adjusted_hedges_g, lower = adjusted_lower, upper = adjusted_upper)
  ) |>
  mutate(significant = ifelse(lower > 0, "Significant", "Non-significant"))

```

# Specification curves/multiverse analyses

## Original

```{r fig.height=5, fig.width=6}

data_estimate_plot_original <- data_combined |>
  filter(study == "original") |>
  arrange(hedges_g) |>
  mutate(rnk = row_number())

data_median_es_original <- data_combined |>
  filter(study == "original") |>
  summarize(median_es = median(hedges_g))

p_estimates_original <- 
  ggplot(data_estimate_plot_original, aes(rnk, hedges_g, color = significant)) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_hline(data = data_median_es_original,
             aes(yintercept = median_es), linetype = "solid", color = "orange") +
  geom_point(shape = "square", size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper)) +
  scale_y_continuous(breaks = scales::breaks_width(0.5)) + 
  ylab("Hedges' g") +
  theme_classic() +
  theme(axis.line.x = element_blank(),
        legend.position = "none",
        strip.placement = "outside",
        strip.background = element_rect(fill = NA, colour = NA),
        panel.spacing.x = unit(0.15, "cm"),
        strip.text.y = element_markdown(angle = 180, face = "bold", size = 7),
        axis.text.y = element_text(angle = 0, 
                                   hjust = 0.5, 
                                   size = 6),
        axis.title.y = element_text(size = 9, face = "bold"),
        panel.spacing = unit(0.25, "lines"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_viridis_d(begin = 0.3, end = 0.7)

data_spec_plot_original <- data_combined |> 
  filter(study == "original") |>
  arrange(hedges_g) |>
  mutate(rnk = row_number()) |>
  mutate(Interval = as.factor(interval),
         Outcome = as.factor(outcome_measure),
         Baseline = as.factor(control_for_baseline),
         Bonferroni = as.factor(multiple_testing_corrections)) |>
  dplyr::select(Interval, Outcome, Baseline, Bonferroni, rnk) |> 
  tidyr::pivot_longer(c(Interval, Outcome, Baseline, Bonferroni)) |> 
  arrange(rnk)

p_specs_original <- 
  ggplot(data_spec_plot_original, aes(x = rnk, y = factor(value), color = name)) + 
  geom_point(size = 2, shape = "square") +
  facet_grid(name ~ ., space = "free_y", scales = "free_y", switch = "y") +
  guides(color = "none") +
  #scale_x_continuous(NULL, expand = c(.01, .01)) +
  ylab("Analytic choices") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill = NA, colour = NA),
        panel.spacing.x = unit(0.15, "cm"),
        strip.text.y = element_markdown(angle = 180, face = "bold", size = 7),
        axis.text.y = element_text(angle = 0, hjust = 0.5, size = 6),
        axis.title.y = element_text(size = 9, face = "bold"),
        panel.spacing = unit(0.25, "lines"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_brewer(palette = "Dark2")


p_estimates_original + p_specs_original + plot_layout(ncol = 1, heights = c(0.7, 1))

```


## Replication

```{r fig.height=5, fig.width=6}

data_estimate_plot_replication <- data_combined |>
  filter(study == "replication") |>
  arrange(hedges_g) |>
  mutate(rnk = row_number())

data_median_es_replication <- data_combined |>
  filter(study == "replication") |>
  summarize(median_es = median(hedges_g))

p_estimates_replication <- 
  ggplot(data_estimate_plot_replication, aes(rnk, hedges_g, color = significant)) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_hline(data = data_median_es_replication,
             aes(yintercept = median_es), linetype = "solid", color = "orange") +
  geom_point(shape = "square", size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper)) +
  scale_y_continuous(breaks = scales::breaks_width(0.5)) + 
  ylab("Hedges' g") +
  theme_classic() +
  theme(axis.line.x = element_blank(),
        legend.position = "none",
        strip.placement = "outside",
        strip.background = element_rect(fill = NA, colour = NA),
        panel.spacing.x = unit(0.15, "cm"),
        strip.text.y = element_markdown(angle = 180, face = "bold", size = 7),
        axis.text.y = element_text(angle = 0, 
                                   hjust = 0.5, 
                                   size = 6),
        axis.title.y = element_text(size = 9, face = "bold"),
        panel.spacing = unit(0.25, "lines"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_viridis_d(begin = 0.3, end = 0.7)

data_spec_plot_replication <- data_combined |> 
  filter(study == "replication") |>
  arrange(hedges_g) |>
  mutate(rnk = row_number()) |>
  mutate(Interval = as.factor(interval),
         Outcome = as.factor(outcome_measure),
         Baseline = as.factor(control_for_baseline),
         Bonferroni = as.factor(multiple_testing_corrections)) |>
  dplyr::select(Interval, Outcome, Baseline, Bonferroni, rnk) |> 
  tidyr::pivot_longer(c(Interval, Outcome, Baseline, Bonferroni)) |> 
  arrange(rnk)

p_specs_replication <- 
  ggplot(data_spec_plot_replication, aes(x = rnk, y = factor(value), color = name)) + 
  geom_point(size = 2, shape = "square") +
  facet_grid(name ~ ., space = "free_y", scales = "free_y", switch = "y") +
  guides(color = "none") +
  #scale_x_continuous(NULL, expand = c(.01, .01)) +
  ylab("Analytic choices") +
  theme_classic() +
  theme(strip.placement = "outside",
        strip.background = element_rect(fill = NA, colour = NA),
        panel.spacing.x = unit(0.15, "cm"),
        strip.text.y = element_markdown(angle = 180, face = "bold", size = 7),
        axis.text.y = element_text(angle = 0, hjust = 0.5, size = 6),
        axis.title.y = element_text(size = 9, face = "bold"),
        panel.spacing = unit(0.25, "lines"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_brewer(palette = "Dark2")


p_estimates_replication + p_specs_replication + plot_layout(ncol = 1, heights = c(0.7, 1))

```

# Session info

```{r}

sessionInfo()

```


