---
title: "Analysis of Foody et al. (2012)"
subtitle: "Data processing"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}

knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

```

# Dependencies 

```{r}

# dependencies
library(dplyr)
library(tidyr)
library(readr)
library(forcats)
library(janitor)

# create director
dir.create("../../data/processed/")

# turn off scientific notation
options(scipen = 999)

```

# Get data

```{r}

data_extracted_from_plots <- 
  bind_rows(
    read_csv("../../../data/extracted/foody et al 2012 publication/summary stats extracted from plots/discomfort.csv",
           col_names = FALSE,
           show_col_types = FALSE) |>
      mutate(outcome = "discomfort"),
    read_csv("../../../data/extracted/foody et al 2012 publication/summary stats extracted from plots/anxiety.csv",
           col_names = FALSE,
           show_col_types = FALSE) |>
      mutate(outcome = "anxiety"),
    read_csv("../../../data/extracted/foody et al 2012 publication/summary stats extracted from plots/distress.csv",
           col_names = FALSE,
           show_col_types = FALSE) |>
      mutate(outcome = "distress")
  ) |>
  select(outcome, vars = X1, value = X2) |>
  separate(vars, into = c("timepoint", "type"), sep = " ") |>
  pivot_wider(names_from = type,
              values_from = "value") |>
  rename(mean_reported_in_plot = estimate) |>
  mutate(lower = mean_reported_in_plot - (upper - mean_reported_in_plot))
  
data_combined <- 
  data_extracted_from_plots |>
  mutate(outcome = fct_relevel(outcome, "discomfort", "anxiety", "distress"),
         timepoint = fct_relevel(timepoint, "baseline", "postinduction"),
         n_reported_in_text = 32) |>
  arrange(outcome, timepoint) |>
  select(outcome, 
         timepoint, 
         mean_reported_in_plot, 
         n_reported_in_text,
         interval_upper = upper, 
         interval_lower = lower) |>
  # calculate interval width
  mutate(interval_width_extracted_from_plot = interval_upper - interval_lower,
         interval_lower_width = mean_reported_in_plot - interval_lower,
         interval_upper_width = interval_upper - mean_reported_in_plot)

```

# Calculate SDs

```{r}

data_processed <- data_combined |>
  mutate(
    # SD assuming intervals in plots are 95% CIs
    sd_assuming_ci = (interval_width_extracted_from_plot/(1.96*2)) * sqrt(n_reported_in_text), 
    # SD assuming intervals in plots are SEM
    sd_assuming_sem = interval_width_extracted_from_plot/2 * sqrt(n_reported_in_text)
  ) 

```

# Write to disk

```{r}

dir.create("../../../data/extracted/foody et al 2012 publication/")
dir.create("../../../data/processed/foody et al 2012 publication/")

write_csv(data_processed, "../../../data/extracted/foody et al 2012 publication/data_extracted_all.csv")

data_processed |>
  #filter(timepoint %in% c("postinduction", "postintervention")) |>
  select(outcome, 
         timepoint, 
         n = n_reported_in_text, 
         mean = mean_reported_in_plot, 
         sd_assuming_ci, 
         sd_assuming_sem) |>
  write_csv("../../../data/processed/foody et al 2012 publication/data_processed.csv")

```

# Session info

```{r}

sessionInfo()

```



