---
title: "Analysis of Foody et al. (2013)"
subtitle: "Data processing"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}

knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

```

# Dependencies 

```{r}

# dependencies
library(dplyr)
library(readr)
library(janitor)

# create director
dir.create("../../data/processed/")

```

# Get data

```{r}

data_extracted <- read_csv("../../data/raw/extracted summary statistics.csv")

```

# Calculate summary stats

```{r}

data_processed <- data_extracted |>
  group_by(outcome) |>
  mutate(recalculated_mean = round_half_up(lag(extracted_mean, 2) + reported_difference_score, 2)) |>
  ungroup() |>
  mutate(extracted_mean_recalculated_mean_diff = extracted_mean - recalculated_mean, # to assess the magnitude of differences between the two approaches. Always ±.6 on a 0-100 scale.
         sd_assuming_ci = (extracted_interval_width/(1.96*2)) * sqrt(reported_n), # SD assuming intervals in plots are 95% CIs
         sd_assuming_sem = extracted_interval_width * sqrt(reported_n)) # SD assuming intervals in plots are SEM

```

# Write to disk

```{r}

write_csv(data_processed, "../../data/processed/data_processed.csv")

```

# Session info

```{r}

sessionInfo()

```



